# pull official base image
FROM python:3.8-slim-buster

# set work directory
RUN mkdir -p /home/psa/app
WORKDIR /home/psa/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENV prod

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /home/psa/app/requirements.txt
RUN pip install -r /home/psa/app/requirements.txt
RUN yes |apt-get update
RUN yes |apt-get -y install curl
RUN yes |apt-get install wkhtmltopdf

# copy project
COPY . /home/psa/app/

ENTRYPOINT ["/home/psa/app/entrypoint-prod.sh"]